/* Auto-generated by cbindgen. Do not edit. */

#ifndef XVISIO_H
#define XVISIO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define VID 1038

#define PID 62472

#define HID_INTERFACE 3

#define SLAM_ENDPOINT 131

#define REPORT_SIZE 63

/**
 * Fixed-point scale factor: 2^(-14) = 1/16384.
 */
#define SCALE 6.103515625e-05

#define PREFIX_HOST_TO_DEVICE 2

#define PREFIX_DEVICE_TO_HOST 1

/**
 * Opaque device handle for C consumers.
 */
typedef struct XvDevice XvDevice;

/**
 * Opaque SLAM stream handle for C consumers.
 */
typedef struct XvSlamStream XvSlamStream;

/**
 * Device info in C-compatible layout.
 */
typedef struct XvDeviceInfo {
    /**
     * Null-terminated UUID string.
     */
    char uuid[64];
    /**
     * Null-terminated version string.
     */
    char version[128];
    /**
     * Feature bitmap.
     */
    uint32_t features;
    /**
     * USB bus identifier (first 32 chars).
     */
    char bus_id[32];
    /**
     * USB device address.
     */
    uint8_t address;
} XvDeviceInfo;

/**
 * Pose data in C-compatible layout.
 */
typedef struct XvPose {
    /**
     * Translation [x, y, z] in meters.
     */
    double translation[3];
    /**
     * Rotation matrix, flat row-major (9 elements).
     */
    double rotation[9];
    /**
     * Quaternion [qx, qy, qz, qw].
     */
    double quaternion[4];
    /**
     * Edge timestamp in microseconds.
     */
    uint64_t timestamp_us;
    /**
     * Host steady-clock timestamp in seconds.
     */
    double host_timestamp_s;
    /**
     * Tracking confidence [0..1].
     */
    double confidence;
    /**
     * Euler angles [roll, pitch, yaw] in degrees.
     */
    double euler_deg[3];
} XvPose;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * List connected XR50 devices.
 *
 * Writes up to `max` entries into `out`. Returns the number of devices found,
 * or -1 on error.
 *
 * # Safety
 * `out` must point to an array of at least `max` `XvDeviceInfo` elements, or be null.
 */
int xv_list_devices(struct XvDeviceInfo *out, int max);

/**
 * Open the first available XR50 device.
 * Returns NULL on error (check xv_last_error()).
 */
struct XvDevice *xv_open_first(void);

/**
 * Open a specific XR50 device by its info.
 * Returns NULL on error.
 *
 * # Safety
 * `info` must point to a valid `XvDeviceInfo`, or be null.
 */
struct XvDevice *xv_open_device(const struct XvDeviceInfo *info);

/**
 * Close a device and free its resources.
 *
 * # Safety
 * `dev` must be a pointer returned by `xv_open_first` or `xv_open_device`, or null.
 */
void xv_close_device(struct XvDevice *dev);

/**
 * Get the device UUID. Returns a pointer to a null-terminated string
 * valid for the lifetime of the device.
 *
 * # Safety
 * `dev` must be a valid device pointer, or null.
 */
const char *xv_device_uuid(const struct XvDevice *dev);

/**
 * Get the device firmware version string.
 *
 * # Safety
 * `dev` must be a valid device pointer, or null.
 */
const char *xv_device_version(const struct XvDevice *dev);

/**
 * Get the device feature bitmap.
 *
 * # Safety
 * `dev` must be a valid device pointer, or null.
 */
uint32_t xv_device_features(const struct XvDevice *dev);

/**
 * Start SLAM streaming.
 * `mode`: 0 = Edge, 1 = Mixed.
 * Returns NULL on error.
 *
 * # Safety
 * `dev` must be a valid device pointer, or null.
 */
struct XvSlamStream *xv_start_slam(struct XvDevice *dev, int mode);

/**
 * Receive the next SLAM pose with timeout.
 * `timeout_ms`: timeout in milliseconds (0 = try without blocking, -1 = block forever).
 * Returns 0 on success, -1 on error/timeout.
 *
 * # Safety
 * `stream` and `pose` must be valid pointers, or null.
 */
int xv_slam_recv(struct XvSlamStream *stream, struct XvPose *pose, int timeout_ms);

/**
 * Check if the SLAM stream is still active.
 *
 * # Safety
 * `stream` must be a valid stream pointer, or null.
 */
bool xv_slam_is_active(const struct XvSlamStream *stream);

/**
 * Stop a SLAM stream and free its resources.
 *
 * # Safety
 * `stream` must be a pointer returned by `xv_start_slam`, or null.
 */
void xv_stop_slam(struct XvSlamStream *stream);

/**
 * Get the last error message. Returns NULL if no error.
 * The returned pointer is valid until the next xvisio API call.
 */
const char *xv_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* XVISIO_H */
